### ISSUE TITLE
Add spell check

### ISSUE THREAD

**Issue by williambout** [williambout/paper-for-mac#3]

**Comment by caloon** [comment]
Not sure if that's possible (e.g. via their API), but Grammarly language check would be really cool as well.

**Comment by thebearjew** [comment]
It should be possible to depend on the native system spellchecking no?

Does Electron provide an API for this?

**Comment by williambout** [comment]
Electron doesn't provide an API for the native spellchecking yet.
@michael-lefebvre is supposed to post a blog post soon about this soon.

**Comment by michael-lefebvre** [comment]
Oops, sounds like I forget to do my homework 😓

I don't have time for a step-by-step post, so to do it simple you need to add the [electron-spell-check-provider](https://github.com/mixmaxhq/electron-spell-check-provider) package to your project.

This is a basic but decent spellcheck provider. I would like to test [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) who seems more complete, but I don't have time now.

Anyway, the BIG issue that is not documented is that you need to rebuild electron's dependencies.

So you must use [electron-rebuild](https://github.com/electron/electron-rebuild) and add the next script to your task runner and execute it after every package install/update.

    var pathToElectron  = require('electron-prebuilt')

    var electronVersion = childProcess.execSync(`${pathToElectron} --version`, {
      encoding: 'utf8',
    })

    return electronRebuild.default( path.join( __dirname, 'app'), electronVersion)
      .then(() => console.info('Rebuild Successful'))
      .catch((e) =>
      {
        console.error("Building modules didn't work!")
        console.error(e)
      })
  
Then "c'est dans la poche", simply copy/adapt [this snippet](https://github.com/mixmaxhq/electron-spell-check-provider#but-how-do-i-show-spelling-suggestions-in-the-context-menu) and it should works. 🙂

Tell me if it's ok or if you have any questions

**Comment by williambout** [comment]
Thanks @michael-lefebvre!
I decided to go with [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) since it was really quick to implement and didn't require to rebuild electron.
