### ISSUE TITLE
Allow adding folders to side bar - Feature request

### ISSUE THREAD

**Issue by zeroby0** [williambout/paper-for-mac#7]
Ability to add folders to side bar will be incredibly helpful.

Like `notes` in the following picture.  

![paper](https://cloud.githubusercontent.com/assets/16903044/26797378/5cd51e1e-4a4a-11e7-9cf4-915b1adc7545.png)

Thanks :)

**Comment by tonyxu-io** [comment]
As I understand, this app is just a wrapping of dropbox web version, the author is not capable of modifying dropbox paper features.
